### ISSUE TITLE
Memory Warning

### ISSUE THREAD

**Issue by dixiedream** [CyberAgent/AMBTableViewController#4]
Hi, thanks for your awesome work! This project is a beast!

I'm trying to place a mapView into a cell but everytime the tableview is scrolled then the controller reloads the section (bypassing the !_section control block) throwing a memory warning exception in no time.
Any way i can avoid this??!

Thanks

**Comment by rivera-ernesto** [comment]
Did you find the problem?

**Comment by dixiedream** [comment]
I solved it using a flag on my custom cells classes. Thanks for your help.

Alessandro Lucarini
dixiedream@hotmail.it

**Comment by rivera-ernesto** [comment]
Good to hear that.
